CREATE TABLE `APP_ACTIVITY` (
  `ACTIVITE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AGE` bigint(20) NOT NULL,
  `STATUS` enum('PUBLIC','DRAFT') NOT NULL,
  `DATE_PUBLICATION` date NOT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (ACTIVITE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_ACTUALITY_CHILD` (
  `ACTUALITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHILD_ID_FK` bigint(20) DEFAULT NULL,
  `FILE_ID_FK` bigint(20) DEFAULT NULL,
  `COMMENTAIRE` varchar(255) NOT NULL,
  `TYPE` enum('INFO','ATTENTION','ACTIVITE') DEFAULT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (ACTUALITY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_CHILD` (
  `CHILD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARENT_USER_ID_FK` bigint(20) DEFAULT NULL,
  `PRENOM` varchar(50) NOT NULL,
  `PICTURE_ID_FK` bigint(20) DEFAULT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `SEXE` enum('GARCON','FILLE') DEFAULT NULL,
  `STATUS` enum('ACCEPTED','ONLOAD','REFUSED','IGNORED','NEW') DEFAULT NULL,
  `TRAINING_CENTER_ID_FK` bigint(20) DEFAULT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  `CODE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (CHILD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_FILE` (
  `FILE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FILE_NAME` varchar(100) DEFAULT NULL,
  `PATH` varchar(100) DEFAULT NULL,
  `TYPE` enum('ADMIN','PARENT','CENTER') DEFAULT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  `USER_ID_FK` bigint(20) DEFAULT NULL,
  PRIMARY KEY (FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_ROLE` (
  `ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID_FK` bigint(20) NOT NULL,
  `ROLE` enum('ADMIN','PARENT','FORMATION') DEFAULT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_TRAINING_CENTER` (
  `CENTER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CENTER_NAME` varchar(255) NOT NULL,
  `LOGO_FILE_ID_FK` bigint(20) DEFAULT NULL,
  `MANAGER_USER_ID_FK` bigint(20) DEFAULT NULL,
  `ADDRESS` varchar(255) NOT NULL,
  `VILLE` varchar(255) NOT NULL,
  `COUNTRY` varchar(255) NOT NULL,
  `PHONE` varchar(255) NOT NULL,
  `STATUS` enum('REQUEST','SUSPENDED','VALIDATE') NOT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (CENTER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `APP_USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOM` varchar(50) NOT NULL,
  `PRENOM` varchar(50) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `STATUS` enum('SIGNUP','VALIDATE','SUSPENDED') NOT NULL,
  `USER_PASSWORD` varchar(100) DEFAULT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `USER_PICTURE_FILE` bigint(20) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(20) DEFAULT NULL,
  `PHONE` varchar(20) DEFAULT NULL,
  `FACEBOOK_ID` varchar(255) DEFAULT NULL,
  `GOOGLE_ID` varchar(255) DEFAULT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATING_DATE` timestamp NULL DEFAULT NULL,
  `DELETING_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;


UPDATE `APP_CHILD` SET `BIRTH_DATE` = DATE(NOW()) WHERE `BIRTH_DATE` = NULL;
ALTER TABLE `APP_CHILD` CHANGE `BIRTH_DATE` `BIRTH_DATE` DATE NOT NULL;
ALTER TABLE `APP_USER` ADD `VILLE` VARCHAR(25) NULL AFTER `ADDRESS`;
