version: "3"

networks:
  network:
    driver: bridge

services:


  dev_database:
    container_name: dev_mysql
    image: mysql:5.7
    volumes:
      - ./mount/data/dev/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=all0.1EN2.3ce
    networks:
      - network
  adminDB:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.7.7-1
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://admindb.allence-tunisie.com
    depends_on:
      - dev_database
    ports:
      - 82:80
    links:
      - dev_database:dev_db
    networks:
      - network
  portainer:
    container_name: vision
    image: portainer/portainer
    ports:
      - 84:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mount/data/vision/:/data portainer/portainer
    networks:
      - network
  proxy:
    container_name: nginx
    image: nginx
    volumes: # mount custom config at runtime
      - ./mount/config-dev/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./mount/data/front/:/usr/share/nginx/html/
    depends_on:
      - adminDB
    links:
      - adminDB:phpmyadmin
      - portainer:vision
      - dev_database:dev_mysql
    ports:
      - 85:80
    networks:
      - network
  Selenuim:
    container_name: chrome
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
