CREATE TABLE IF NOT EXISTS APP_NOTIFICATION (
  NOTIFICATION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  STATUS enum('LUS','NON_LUS','ARCHIVES') NOT NULL,
  TYPE enum('CREATION','REFUSE','ACCEPTATION','CONTACT') NOT NULL,
  DESTINATION_ID_FK BIGINT(20) NULL,
  DESTINATION_URL VARCHAR(255) NULL,
  TITLE VARCHAR(255) NOT NULL,
  CHILD_ID_FK BIGINT(20) NULL,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATING_DATE TIMESTAMP NULL DEFAULT NULL,
  DELETING_DATE TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (NOTIFICATION_ID)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;



